language: python
env:
  - PYTHON_VERSION=3.4
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - wget -q https://github.com/marbl/Mash/releases/download/v2.0/mash-Linux64-v2.0.tar
  - tar -xf mash-Linux64-v2.0.tar
  - mkdir -p $HOME/usr/bin && mv mash-Linux64-v2.0/mash $HOME/usr/bin/mash
  - export PATH=$HOME/miniconda/bin:$HOME/usr/bin:$PATH
install:
  - conda create -q -y -n genbank-qc -c etetoolkit python=$PYTHON_VERSION --file=ci/conda-requirements.txt
  - source activate genbank-qc
  - pip install -q . --no-deps
script:
  - pytest -v