language: python
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget -q https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
        wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda && . /$HOME/miniconda/etc/profile.d/conda.sh
  - wget -P /home/travis/miniconda/envs/genbankqc/lib https://github.com/openwebos/qt/tree/master/lib/fonts
install:
  - conda env create -q -n genbankqc -f requirements/conda.yaml
  - conda activate genbankqc
  - pip install -q . --no-deps
  - pip install flake8
  - pip install pytest
script:
  - pytest
  - flake8
