channels:
  - conda-forge
  - bioconda
  - biocore
dependencies:
  - python==3.6.6
  - click==7.0
  - ete3==3.1.1
  - scikit-bio==0.5.4
  - biopython==1.72
  - pandas==0.22.0
  - numpy==1.15.2
  - snakemake
  - mash==2.1
  - entrez-direct==10.2
